const String HomeAppBarTitle = "To-Do List";
const String AddAppBarTitle = "Add new To-Do List";
const String AddHeaderTitle = "To-Do Title";
const String AddHeaderStartDate = "Start Date";
const String AddHeaderEndDate = "Estimated End Date";
const String AddBtnTitle = "Create Now";
const String AddTodoTextfieldHint = "Please key in your To-Do title here";
const String UpdateAppBarTitle = "Update To-Do List";
const String UpdateBtnTitle = "Update Now";